name: Dart CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  # flutter_version: "1.12.13+hotfix.5"
  java_version: "12.x"

jobs:
  test:
    name: Flutter Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - run: |
          pwd
          cd $GITHUB_REPOSITORY
          pwd
          cd .fvm
          pwd
          cat fvm_config.json
      - name: Setup environment variables
        shell: bash
        run: |
          echo ::set-env name=RUNNER_TOOL_CACHE::$(echo "$RUNNER_TOOL_CACHE")
          echo ::set-env name=flutter_version::$(cat "$GITHUB_REPOSITORY/.fvm/fvm_config.json" | jq '.["flutterSdkVersion"]' -r)
      # - uses: actions/setup-java@v1
      #   with:
      #     java-version: "12.x"
      # - name: Cache Flutter dependencies
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{env.RUNNER_TOOL_CACHE}}/flutter
      #     key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      # - uses: subosito/flutter-action@v1
      #   with:
      #     flutter-version: ${{ env.flutter_version }}
      #     # channel: "stable"
      # - run: dart --version
      # - run: flutter --version
